function showcase(){var fb='',R=' top: -1000px;',ob='" for "gwt:onLoadErrorFn"',mb='" for "gwt:onPropertyErrorFn"',$='");',pb='#',sc='.cache.js',rb='/',xb='//',Zb='06CE5D6D82E2BB6D5AF3242D00856335',$b='0ADC77482455496F22A3E1BE53B079EE',_b='157AD79A8C80EB9F2451DA68120C5871',ac='2D68848CA64A930150FFE62BE88855CD',bc='55CBAA1CB143DC164BA300868DF322BB',cc='705198A23B87A477A8D67164F18BF330',dc='71612C0AEDE36E864AAC30255DBBAF58',ec='833240BE720EA83768CBA32620A209DA',fc='836994CD402AE2345AF0B8BF78A6DE03',gc='8808C238119F4303D50680D4C2A16116',hc='8DE5E4EDD30D2BF24F3D6601A705EA07',ic='96ADC627E8926C118F720D7826BABB8F',jc='9FDC180427F45F7380A6BF3A695EA4B3',rc=':',gb='::',S='<html><head><\/head><body><\/body><\/html>',jb='=',qb='?',kc='A0A6394AF19B7B74221607CE13ECA272',lc='B423F2A51B02278A59C3DCE86ECCD3C9',lb='Bad handler "',mc='CFC3B639B2387EDA0D4E160F795E4FC1',Y='Chrome',X='DOMContentLoaded',M='DUMMY',nc='E0DBD85E5C3A09AFAA7147BB5DE2C1B6',oc='E7EB8054213EDBC86A1214FFD127AE50',pc='E8918DDA5F83873F1AF3F18B9CD15FDA',qc='F036C4F721ECC0911D985894EBCA7C73',zb='android',Bb='android_tablet',wb='base',ub='baseUrl',H='begin',Hb='blackberry',N='body',G='bootstrap',tb='clear.cache.gif',ib='content',Ib='desktop',uc='end',Z='eval("',Ub='gecko',Vb='gecko1_8',I='gwt.codesvr.showcase=',J='gwt.codesvr=',nb='gwt:onLoadErrorFn',kb='gwt:onPropertyErrorFn',hb='gwt:property',bb='head',Tb='ie6',Sb='ie8',Rb='ie9',O='iframe',sb='img',Cb='ipad',Db='ipad_retina',Eb='iphone',Fb='ipod',U='javascript',P='javascript:""',tc='loadExternalRefs',cb='meta',yb='mgwt.os',Ab='mobile',Jb='mobile.user.agent',Kb='mobilesafari',ab='moduleRequested',_='moduleStartup',Qb='msie',db='name',Lb='not_mobile',Nb='opera',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Gb='retina',Pb='safari',T='script',Xb='selectingPermutation',K='showcase',Yb='showcase.devmode.js',vb='showcase.nocache.js',eb='showcase::',L='startup',W='undefined',Wb='unknown',Mb='user.agent',V='var $wnd = window.parent;',Ob='webkit';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
showcase.__sendStats=r;showcase.__moduleName=K;showcase.__errFn=null;showcase.__moduleBase=M;showcase.__softPermutationId=0;showcase.__computePropValue=null;showcase.__getPropMap=null;showcase.__gwtInstallCode=function(){};showcase.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close();var b=v.getElementsByTagName(N)[0];var c=v.createElement(T);c.language=U;var d=V;c.text=d;b.appendChild(c)}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(T);g.language=U;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(T);g.language=U;g.text=c[i];e.appendChild(g);d(e,g)}}}
showcase.onScriptDownloaded=function(a){l(function(){m(a)})};r(_,ab);var n=p.createElement(T);n.src=k;p.getElementsByTagName(bb)[0].appendChild(n)}
showcase.__startLoadingFragment=function(a){return C(a)};showcase.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(T);c.language=U;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(cb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(db),k;if(j){j=j.replace(eb,fb);if(j.indexOf(gb)>=0){continue}if(j==hb){k=i.getAttribute(ib);if(k){var l,m=k.indexOf(jb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=fb}c[j]=l}}else if(j==kb){k=i.getAttribute(ib);if(k){try{d=eval(k)}catch(a){alert(lb+k+mb)}}}else if(j==nb){k=i.getAttribute(ib);if(k){try{e=eval(k)}catch(a){alert(lb+k+ob)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;showcase.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(pb);if(b==-1){b=a.length}var c=a.indexOf(qb);if(c==-1){c=a.length}var d=a.lastIndexOf(rb,Math.min(c,b));return d>=0?a.substring(0,d+1):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(sb);b.src=a+tb;a=e(b.src)}return a}
function g(){var a=t(ub);if(a!=null){return a}return fb}
function h(){var a=p.getElementsByTagName(T);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(vb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=p.getElementsByTagName(wb);if(a.length>0){return a[a.length-1].href}return fb}
function j(){var a=p.location;return a.href==a.protocol+xb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return showcase.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[yb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(zb)!=-1){if(a.indexOf(Ab)!=-1){return zb}else{return Bb}}if(a.indexOf(Cb)!=-1){if(window.devicePixelRatio>=2){return Db}return Cb}if(a.indexOf(Eb)!=-1||a.indexOf(Fb)!=-1){if(window.devicePixelRatio>=2){return Gb}return Eb}if(a.indexOf(Hb)!=-1){return Hb}return Ib}();return b}};i[yb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};j[Jb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Kb:Lb};i[Jb]={mobilesafari:0,not_mobile:1};j[Mb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Nb)!=-1}())return Nb;if(function(){return b.indexOf(Ob)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=9}())return Rb;if(function(){return b.indexOf(Qb)!=-1&&p.documentMode>=8}())return Sb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Tb;if(function(){return b.indexOf(Ub)!=-1}())return Vb;return Wb};i[Mb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};showcase.__getPropMap=function(){var a={};for(var b in i){a[b]=k(b)}return a};showcase.__computePropValue=k;o.__gwt_activeModules[K].bindings=showcase.__getPropMap;r(G,Xb);if(q()){return C(Yb)}var l;try{h([Hb,Kb,Pb],Zb);h([Ib,Lb,Sb],$b);h([Gb,Kb,Pb],_b);h([Ib,Lb,Vb],ac);h([Gb,Lb,Pb],bc);h([Eb,Kb,Pb],cc);h([zb,Kb,Pb],dc);h([Ib,Lb,Pb],ec);h([Hb,Lb,Pb],fc);h([Cb,Kb,Pb],gc);h([Bb,Lb,Pb],hc);h([Cb,Lb,Pb],ic);h([Ib,Kb,Pb],jc);h([Db,Lb,Pb],kc);h([Ib,Lb,Rb],lc);h([Bb,Kb,Pb],mc);h([Eb,Lb,Pb],nc);h([Ib,Lb,Nb],oc);h([zb,Lb,Pb],pc);h([Db,Kb,Pb],qc);l=f[k(yb)][k(Jb)][k(Mb)];var m=l.indexOf(rc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}showcase.__softPermutationId=g;return C(l+sc)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(tc,H);r(tc,uc)}
A();showcase.__moduleBase=B();u[K].moduleBase=showcase.__moduleBase;var F=D();E();r(G,uc);z(F);return true}
showcase.succeeded=showcase();